Shells for declerative package managers guix and nix
tauri-apps/wry pull request #1378
Opened 2024-10-01 17:29 UTC by pelasgus

Concerning:
- https://github.com/tauri-apps/wry/pull/1377
- https://github.com/tauri-apps/wry/pull/1373
- https://github.com/tauri-apps/wry/pull/990

> [!NOTE]
> **N.B.**: Im willing to transfer the repo to the organisation for easier management and future updates and maintenance. Its easier overall for it to be a submodule.

> [!IMPORTANT]
> **P.S.**: Will be adding a flake for `nix` as well.

@amrbashir was the original reviewer. please when you have a minute, check this out.

2021-03-23 08:56 UTC, wusyong commented
Evergreen distribution is the [recommended ](https://docs.microsoft.com/zh-tw/microsoft-edge/webview2/concepts/distribution#evergreen-distribution-mode)way for most scenarios as Microsoft states.
I think it's better for this crate to stick with it to prevent more complex version issues.
After the April update, Windows 10 will have webview2 runtime by default.
As for older versions like Windows 7 and 8, there's an evergreen bootstrapper in the link you post which can provide to users.
We will offer this check in Tauri if users don't have webview2 runtime yet.

2021-03-23 09:19 UTC, geolehmann commented
okay, I agree with this, thanks.

2021-03-23 09:23 UTC, nothingismagick commented
I agree that this should not be WRY's concern. Adding a binary delivery mechanism is out of scope (for wry). That said, I think that Tauri should consider offering this as an option in its MS bundler configuration. To that end I have transferred this issue and renamed.

2024-10-01 17:33 UTC, pelasgus commented
If you do take ownership of the repository, then we could perhaps make the shells a little bit more universal so that they could be employed by all tauri repos; thus making development much easier.

2024-10-02 00:50 UTC, amrbashir requested changes

2024-10-02 00:50 UTC, amrbashir commented on README.md
> +> [!IMPORTANT]
let's remove this info, it is outdated and not a concern for this repo anymore

2024-10-02 00:50 UTC, amrbashir commented on README.md
> +> [!WARNING]
ditto, this info is no longer needed and should be removed

2024-10-02 00:50 UTC, amrbashir commented on README.md
> +      libappindicator-gtk3
these two packages are no longer a concern for this repo, we should remove them from here

2024-10-02 00:50 UTC, amrbashir commented on README.md
> + > Guix does not have the Ayatana package yet, so you need to use the GTK one, see the [feature flags documentation](https://docs.rs/wry/latest/wry/#feature-flags).
This is not needed and the submodule as well, the instructions at Line 104 are enough

2024-10-13 01:09 UTC, amrbashir commented on README.md
> +> If `nix` and/if `nix-darwin` are used then follow instructions from [Nix Section](#nix--nixos).
Nix section uses webkit2gtk where on macOS we use the included WKWebView, let's remove this

2024-10-14 03:05 UTC, amrbashir approved these changes

2024-10-14 03:05 UTC, merged