feat: Allow setting extension path for Windows and Linux
tauri-apps/wry pull request #1403
Opened 2024-10-28 01:06 UTC by SpikeHD

Introduces `with_extension_path`, which is now used by Windows and Linux to load extensions from.

Linux doesn't include `browser_extensions_enabled` because there is no setting to turn them on or off in WebkitGTK, only to set their directory. I assume if no directory is set, then no extensions are loaded from anywhere, so the option would be redundant.

2024-10-28 09:56 UTC, amrbashir requested changes

2024-10-28 09:56 UTC, amrbashir commented on .changes/extension-path.md
> +Add `with_extension_path` API to Windows and Linux.
```suggestion
Add `WebViewBuilder::with_extension_path` API on Windows and Linux.
```

2024-10-28 09:56 UTC, amrbashir commented on src/lib.rs
> +  /// Determines the path from which to load extensions from. Extensions stored in this path should be unpacked.
```suggestion
  /// Set the path from which to load extensions from. Extensions stored in this path should be unpacked.
```

2024-10-28 09:56 UTC, amrbashir commented on src/lib.rs
> +  /// Does nothing if browser extensions are disabled.
```suggestion
  /// Does nothing if browser extensions are disabled. See [`with_browser_extensions_enabled`](Self::with_browser_extensions_enabled)
```

2024-10-28 09:56 UTC, amrbashir commented on src/webkitgtk/mod.rs
> +    }
no need to convert to str here
```suggestion
    if let Some(extension_path) = &pl_attrs.extension_path {
      web_context.os.set_web_extensions_directory(extension_path);
    }
```

2024-10-28 09:56 UTC, amrbashir commented on src/webkitgtk/web_context.rs
> +  }
```suggestion
  pub fn set_web_extensions_directory(&mut self, path: &Path) {
    self.context.set_web_extensions_directory(path.to_string_lossy());
  }
```

2024-10-28 09:56 UTC, amrbashir commented on src/webview2/mod.rs
> +    }
let's move the unsafe block a little bit below

```suggestion
    if pl_attrs.browser_extensions_enabled {
      if let Some(extension_path) = pl_attrs.extension_path {
        unsafe { Self::load_extensions(&webview, &extension_path)? };
      }
    }
```

2024-10-28 09:56 UTC, amrbashir commented on src/webview2/mod.rs
> +    if let Some(extension_path) = extension_path.to_str() {
no need to call `to_str` here, just pass ito `fs::read_dir` directly.

2024-10-28 09:56 UTC, amrbashir commented on src/webview2/mod.rs
> +        if let Some(path_str) = path_str {
no need to convert to str her as well, just do
```rs
let path_hs = HSTRING::from(path);
```

2024-10-28 16:49 UTC, amrbashir commented on src/webview2/mod.rs
> +      let path_hs = HSTRING::from(path);
```suggestion
      let path_hs = HSTRING::from(path.as_path());
```

2024-10-28 16:49 UTC, amrbashir approved these changes, later dismissed

2024-10-28 16:49 UTC, amrbashir commented
Thank you

2024-10-28 16:55 UTC, amrbashir commented
Oh looks like you didn't sign your commits and I can't merge the PR unless they are signed. You need to setup [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), then you can sign past commit like [this](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits/1123928#1123928). `git rebase --exec 'git commit --amend --no-edit -n -S' -i dev`

2024-10-28 17:09 UTC, SpikeHD commented
One day I will remember to add `-S` when committing. Today was not that day

2024-10-28 17:13 UTC, amrbashir commented
> One day I will remember to add `-S` when committing. Today was not that day

🤣 , I have my global `.gitconfig` to always sign so I don't forget
```
[commit]
    gpgsign = true
```

2024-10-28 17:28 UTC, amrbashir approved these changes

2024-10-28 17:28 UTC, merged

2024-11-19 20:10 UTC, zhangsan2lisi commented
```
fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .build(&event_loop)
        .expect("failed to create window");
    let path = PathBuf::from("test");
    let mut context = WebContext::new(Some(path));
    let webview = WebViewBuilder::with_web_context(&mut context)
        .with_url("https://google.com/")
        // .with_browser_extensions_enabled(true)
        .with_extension_path(PathBuf::from("Extensions/6.6.3_0"))
        .build(&window)
        .expect("could not create webview");
    webview.open_devtools();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Poll;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
                ..
            } => {
                *control_flow = ControlFlow::Exit;
            }
            _ => {}
        }
    });
}
```
@SpikeHD  @amrbashir 
First of all, thank you for implementing this function

I attempted to launch a window to load the following extension: https://microsoftedge.microsoft.com/addons/detail/vuejs-devtools/olofadcdnkkjdfgjcmjaadnlehnnihnl
 I have already unpacked and repackaged the extension. When tested using Chromium in Electron with the following arguments, it works perfectly fine:
args: [ 
  `--disable-extensions-except=${extensionPath}`,
  `--load-extension=${extensionPath}`,
  "--no-sandbox",
  "--disable-sync",
]

However, when I use Wry on Windows and call .with_extension_path() to load this extension, it fails. Additionally, the extension folder (olofadcdnkkjdfgjcmjaadnlehnnihnl) does not appear in the test\EBWebView\Default\Extensions directory.

When I attempt to enable both .with_browser_extensions_enabled(true) and .with_extension_path(PathBuf::from("Extensions/6.6.3_0")) simultaneously, it results in the following error:
WebView2Error(WindowsError(Error { code: HRESULT(0x80004003), message: "Invalid pointer" })).

Even when I only enable .with_browser_extensions_enabled(true), the extension still does not work.

How can I resolve this issue? Thank you again for helping me.

2024-11-19 23:10 UTC, SpikeHD commented
I've done some digging, and it seems `ICoreWebView2Profile7::AddBrowserExtension` doesn't like being passed `None` as the completion handler, which is what's causing `Invalid pointer`.

Changing that to have an empty handler function fixes your example:

`src/webview2/mod.rs L1195`
```rust
    // Iterate over all folders in the extension path
    for entry in fs::read_dir(extension_path)? {
      let path = entry?.path();
      let path_hs = HSTRING::from(path.as_path());
      let handler = ProfileAddBrowserExtensionCompletedHandler::create(Box::new(|_, _| Ok(())));

      profile.AddBrowserExtension(&path_hs, &handler)?;
    }
```

Keep in mind @zhangsan2lisi that the path you are providing should be a *folder* where all extensions reside, even if it is just one.

For example, this would fail:

```
extension/
├─ manifest.json
```
```rust
let webview = WebViewBuilder::with_web_context(&mut context)
    .with_extension_path(PathBuf::from("extension"))
```
but this would succeed:
```
extensions/
├─ my_extension/
│  ├─ manifest.json
```
```rust
let webview = WebViewBuilder::with_web_context(&mut context)
    .with_extension_path(PathBuf::from("extensions"))
```
because the function reads the files within the provided directory as extensions, not the folder itself.

I will make a PR soon to address the `Invalid Pointer` issue, as well as rename the function to `with_extensions_path` so it is less misleading/confusing.

2024-11-20 07:34 UTC, zhangsan2lisi commented
@SpikeHD  Thank you for your help. I have successfully used it.