feat: basic ios support
tauri-apps/wry pull request #238
Opened 2021-05-05 21:14 UTC by lemarier

2021-05-27 13:06 UTC, wusyong requested changes
Could rename `gtkwebview` directory to `webkitgtk`?

2021-05-27 16:24 UTC, wusyong approved these changes

2021-05-27 16:34 UTC, merged

2021-07-05 19:22 UTC, jkelleyrtp commented
Sorry to necro - but do you mind putting together a basic repo with the xcode project stuff configured so we can do a full app build?

2021-07-05 19:56 UTC, lemarier commented
We do have a PoC [here](
https://github.com/lemarier/wry-ios-poc-new). It use [cargo-mobile](https://github.com/BrainiumLLC/cargo-mobile)

2021-07-05 21:56 UTC, jkelleyrtp commented
> We do have a PoC [here](https://github.com/lemarier/wry-ios-poc-new). It use [cargo-mobile](https://github.com/BrainiumLLC/cargo-mobile)

Thanks! Perfect! :)