Implement new window requested event
tauri-apps/wry pull request #526
Opened 2022-03-23 21:31 UTC by atlanticaccent

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

The WKWebview implementation is outstanding but I'm giving it a shot.
Also couldn't test this properly as whilst testing using WSL I couldn't get popup windows to work.

Regardless of the above, these "naïve" implementations may allow for new popup windows to bypass/ignore existing webview settings. For example, they do not inherit parent window navigation handlers for example. This isn't a new thing - it's just more noticeable when implementing a feature like this where we have functions that can cancel events.

2022-04-30 08:12 UTC, amrbashir requested changes
Windows, and Linux implementation is LGTM. There is some small nit-picks and I will leave reviewing the macOS to @wusyong

2022-04-30 08:12 UTC, amrbashir commented on examples/new_window_req_event.rs
> +  webcontext.set_allows_automation(true);
```suggestion
```

2022-04-30 08:12 UTC, amrbashir commented on src/webview/mod.rs
> +  /// allowed to open the url in a new window and false if not.
```suggestion
  /// allow to open the url in a new window and false is not.
```

2022-06-18 03:21 UTC, keiya01 reviewed
It's working great on macos.
it looks good to me.

2022-06-19 08:16 UTC, wusyong submitted a review, later dismissed

2022-06-19 10:10 UTC, amrbashir submitted a review, later dismissed

2022-06-19 10:16 UTC, amrbashir approved these changes

2022-06-19 10:29 UTC, merged