feat: add function to close the devtool and check if it is opened
tauri-apps/wry pull request #529
Opened 2022-03-27 13:42 UTC by lucasfernog

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

This allows an user to implement shortcuts to open/close the devtools.

2022-03-27 14:22 UTC, wusyong submitted a review, later dismissed

2022-03-27 14:57 UTC, amrbashir requested changes
Can we also change all `devtool` to `devtools` in all the functions?

2022-03-27 14:57 UTC, amrbashir commented on src/webview/mod.rs
> +  /// - **Android / iOS:** Not implemented.
```suggestion
  /// - **Android / iOS:** Not supported.
```

2022-03-27 14:57 UTC, amrbashir commented on src/webview/mod.rs
> +  /// - **Windows / Android / iOS:** Not implemented.
```suggestion
  /// - **Windows / Android / iOS:** Not supported.
```

2022-03-27 14:57 UTC, amrbashir commented on src/webview/mod.rs
> +  /// - **Windows / Android / iOS:** Not implemented.
```suggestion
  /// - **Windows / Android / iOS:** Not supported.
```

2022-03-27 14:57 UTC, amrbashir commented on src/webview/wkwebview/mod.rs
> +  /// - **iOS:** Not implemented.
```suggestion
  /// - **iOS:** Not supported.
.
```

2022-03-27 14:57 UTC, amrbashir commented on src/webview/wkwebview/mod.rs
> +  /// - **iOS:** Not implemented, always returns false.
```suggestion
  /// - **iOS:** Not supported.
```

2022-03-27 14:58 UTC, amrbashir commented on src/webview/mod.rs
> +  pub fn is_devtool_visible(&self) -> bool {
```suggestion
  pub fn is_devtool_open(&self) -> bool {
```

2022-03-28 01:38 UTC, amrbashir requested changes

2022-03-28 01:38 UTC, amrbashir commented on .changes/is-devtool-visible.md
> +Added `is_devtools_visible` function to `Webview`.
```suggestion
Added `is_devtools_open` function to `Webview`.
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/android/mod.rs
> +  pub fn is_devtools_visible(&self) -> bool {
```suggestion
  pub fn is_devtools_open(&self) -> bool {
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/mod.rs
> +    self.webview.is_devtools_visible()
```suggestion
    self.webview.is_devtools_open()
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/webkitgtk/mod.rs
> +  is_inspector_visible: Arc<AtomicBool>,
```suggestion
  is_inspector_open: Arc<AtomicBool>,
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/webkitgtk/mod.rs
> +    };
```suggestion
    let is_inspector_open = {
      let is_inspector_open = Arc::new(AtomicBool::default());
      if let Some(inspector) = WebViewExt::inspector(&*webview) {
        let is_inspector_open_ = is_inspector_open.clone();
        inspector.connect_bring_to_front(move |_| {
          is_inspector_open_.store(true, Ordering::Relaxed);
          false
        });
        let is_inspector_open_ = is_inspector_open.clone();
        inspector.connect_closed(move |_| {
          is_inspector_open_.store(false, Ordering::Relaxed);
        });
      }
      is_inspector_open
    };

    let w = Self {
      webview,
      #[cfg(any(debug_assertions, feature = "devtool"))]
      is_inspector_open,
    };
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/webkitgtk/mod.rs
> +      self.is_inspector_visible.store(true, Ordering::Relaxed);
```suggestion
      self.is_inspector_open.store(true, Ordering::Relaxed);
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/webkitgtk/mod.rs
> +    self.is_inspector_visible.load(Ordering::Relaxed)
```suggestion
    self.is_inspector_open.load(Ordering::Relaxed)
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/webview2/mod.rs
> +  pub fn is_devtools_visible(&self) -> bool {
```suggestion
  pub fn is_devtools_open(&self) -> bool {
```

2022-03-28 01:38 UTC, amrbashir commented on src/webview/mod.rs
>    /// but requires `devtool` feature flag to actually enable it in **release** build.
```suggestion
  /// but requires `devtools` feature flag to actually enable it in **release** build.
```
And also changing the actual feature flag name.

2022-03-28 01:38 UTC, amrbashir commented on src/webview/wkwebview/mod.rs
> +  pub fn is_devtools_visible(&self) -> bool {
```suggestion
  pub fn is_devtools_open(&self) -> bool {
```

2022-03-28 02:38 UTC, amrbashir approved these changes, later dismissed

2022-03-28 07:08 UTC, merged