Disable WebView2 mini menu ("OOUI") (fix #535)
tauri-apps/wry pull request #559
Opened 2022-04-25 20:05 UTC by JensMertelmeyer

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Other information
This disables the "mini menu" referenced in #535 by using the `AdditionalBrowserArguments` when creating the WebView2 environment. 

Previously, `CreateCoreWebView2EnvironmentWithOptions(..)` was only called when `data_directory` in `WebContext` was set, otherwise just `CreateCoreWebView2Environment(..)`. I have changed it a bit to always call it "with options", and passing `PWSTR::default()` as a data directory if none was given. 

Existing behaviour has not been changed, just the "mini menu" has been disabled.

2022-04-25 23:29 UTC, amrbashir requested changes
Thanks for taking time to implement this.

2022-04-25 23:29 UTC, amrbashir commented on src/webview/webview2/mod.rs
> +        options = CoreWebView2EnvironmentOptions::default().into();
```suggestion
        let options: ICoreWebView2EnvironmentOptions = CoreWebView2EnvironmentOptions::default().into();
```

2022-04-25 23:29 UTC, amrbashir commented on src/webview/webview2/mod.rs
> +          };
```suggestion
        let data_directory: PWSTR = data_directory.map(|s| pwstr_from_str(&s)).unwrap_or_default();
```

2022-04-26 14:39 UTC, amrbashir submitted a review, later dismissed
LGTM! and It works fine.

2022-04-28 12:09 UTC, wusyong commented
Could you run `cargo fmt`? I'll merge once it's passed formatting CI

2022-04-29 10:14 UTC, merged