WebView2: Enable/disable platform default zooming shortcuts, closes #569
tauri-apps/wry pull request #574
Opened 2022-05-05 19:48 UTC by JensMertelmeyer

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?
By default, platform default zoom is disabled. This will also disable zooming by trackpad or touchscreen which was previously not the case.

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information
I absolutely agree with wry's approach to have default zooming disabled by default. However, I think there are many valid use cases where it makes sense to have the option to enable it.

Thank you for considering.

2022-05-05 20:31 UTC, amrbashir requested changes
Thanks, just some nitpicks to make it more consistent with our style

2022-05-05 20:31 UTC, amrbashir commented on .changes/allow-zooming.md
> +Default: Disabled
```suggestion
Add option to enable/disable zoom shortcuts for WebView2, disabled by default.
```

2022-05-05 20:31 UTC, amrbashir commented on src/webview/mod.rs
> +  pub zoom_enabled: bool,
```suggestion
  /// Whether page zooming by hotkeys is enabled
  ///
  /// ## Platform-specific
  ///
  /// **macOS / Linux / Android / iOS**: Unsupported
  pub zoom_hotkeys_enabled: bool,
```

2022-05-05 20:31 UTC, amrbashir commented on src/webview/mod.rs
> +  pub fn with_zoom(mut self, zoom: bool) -> Self {
```suggestion
  /// Whether page zooming by hotkeys or gestures is enabled
  ///
  /// ## Platform-specific
  ///
  /// **macOS / Linux / Android / iOS**: Unsupported
  pub fn with_hotkeys_zoom(mut self, zoom: bool) -> Self {
```

2022-05-05 20:31 UTC, amrbashir commented on src/webview/webview2/mod.rs
> +
```suggestion
      let settings5 = settings.cast::<ICoreWebView2Settings5>()?;
      let _ = settings5?.SetIsPinchZoomEnabled(attributes.zoom_enabled);
```

2022-05-15 07:17 UTC, amrbashir approved these changes

2022-05-15 07:18 UTC, merged

2022-12-15 18:18 UTC, augustinharter commented
I'm new to tauri; was this feature successfully added and if so how can i enable the zoom shortcuts for my App?