Add the ability to navigate with swipe gesture
tauri-apps/wry pull request #757
Opened 2022-11-16 11:34 UTC by pan93412

On macOS, add an API to enable or disable backward and forward navigation gestures.

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/wry/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Demo video
https://user-images.githubusercontent.com/28441561/202171447-b6cb4750-0326-466f-8e19-3371d996784b.mov

### Other information
The documentation of this function can be seen on <https://developer.apple.com/documentation/webkit/wkwebview/1414995-allowsbackforwardnavigationgestu>.

2022-11-16 11:51 UTC, amrbashir requested changes

2022-11-16 11:51 UTC, amrbashir commented on examples/with_forward_gesture.rs
> +// Copyright 2020-2022 Tauri Programme within The Commons Conservancy
Example is not needed, please remove it.

2022-11-16 11:51 UTC, amrbashir commented on .changes/allow-back-forward-gesture.md
> +For details, see <https://developer.apple.com/documentation/webkit/wkwebview/1414995-allowsbackforwardnavigationgestu>
On macOS, add an API to enable or disable backward and forward navigation gestures.

2022-11-16 12:01 UTC, amrbashir commented on .changes/allow-back-forward-gesture.md
> +For details, see <https://developer.apple.com/documentation/webkit/wkwebview/1414995-allowsbackforwardnavigationgestu>
```suggestion
On macOS, add an API to enable or disable backward and forward navigation gestures.
```

2022-11-16 12:01 UTC, amrbashir approved these changes
Thanks

2022-11-16 14:48 UTC, merged

2025-04-07 09:09 UTC, daveycodez commented
How can I enable this on a new Tauri app for macOS

2025-04-07 09:12 UTC, FabianLars commented
I don't think this was ever exposed in Tauri but you can use this code https://github.com/tauri-apps/wry/pull/757/files#diff-71837c0d08219b9f7bbb5b131c1eba092f7fa5fe6da910b8fd4254b680a17278 in tauri's with_webview method.

2025-04-07 21:51 UTC, daveycodez commented
> I don't think this was ever exposed in Tauri but you can use this code https://github.com/tauri-apps/wry/pull/757/files#diff-71837c0d08219b9f7bbb5b131c1eba092f7fa5fe6da910b8fd4254b680a17278 in tauri's with_webview method.

I'm not totally sure how to use Tauri's with_webview method? I'm pretty new to Rust

2025-04-08 11:32 UTC, FabianLars commented
There's a small example in the docs https://docs.rs/tauri/latest/tauri/webview/struct.WebviewWindow.html#method.with_webview - i think it may be enough to change the `view.setPageZoom()` line to `view.allowsBackForwardNavigationGestures(false)`

2025-04-08 21:03 UTC, daveycodez commented
> There's a small example in the docs https://docs.rs/tauri/latest/tauri/webview/struct.WebviewWindow.html#method.with_webview - i think it may be enough to change the `view.setPageZoom()` line to `view.allowsBackForwardNavigationGestures(false)`

Thanks! This worked.

Here is my /src-tauri/src/lib.rs for anyone who runs into this

```rust
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_http::init())
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }

            let main_webview = app.get_webview_window("main").unwrap();
            let _ = main_webview.with_webview(|webview| {
                #[cfg(target_os = "macos")]
                unsafe {
                    let view: &objc2_web_kit::WKWebView = &*webview.inner().cast();
                    view.setAllowsBackForwardNavigationGestures(true);
                }
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

2025-05-02 11:17 UTC, daveycodez commented
> There's a small example in the docs https://docs.rs/tauri/latest/tauri/webview/struct.WebviewWindow.html#method.with_webview - i think it may be enough to change the `view.setPageZoom()` line to `view.allowsBackForwardNavigationGestures(false)`

How can I make this work on iOS and Android as well? And Windows? It seems really complex. This really should be built into tauri.config